### ISSUE TITLE
__init__.py

### ISSUE THREAD

**Issue by bobdevries** [philkr/CS395T#1]
Looks like the baseline model folders only work if __init__.py is added to the folder

**Comment by philkr** [comment]
ah good catch. I only tried it with python3. I'll add those in a second.

**Comment by bobdevries** [comment]
Thanks!

**Comment by philkr** [comment]
should be fixed. Can you try again?

**Comment by bobdevries** [comment]
It works. Thanks

**Comment by philkr** [comment]
I'll close the issue then.
